// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// iterSS
Rcpp::List iterSS(Rcpp::List ind, Rcpp::List Ur, Rcpp::List Uf, arma::mat Ufull, arma::mat Unull, Rcpp::List Fitted, Rcpp::List Residuals, arma::mat Yh0, arma::mat R0, int k);
RcppExport SEXP _RRPP_iterSS(SEXP indSEXP, SEXP UrSEXP, SEXP UfSEXP, SEXP UfullSEXP, SEXP UnullSEXP, SEXP FittedSEXP, SEXP ResidualsSEXP, SEXP Yh0SEXP, SEXP R0SEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type ind(indSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type Ur(UrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type Uf(UfSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ufull(UfullSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Unull(UnullSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type Fitted(FittedSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type Residuals(ResidualsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Yh0(Yh0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type R0(R0SEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(iterSS(ind, Ur, Uf, Ufull, Unull, Fitted, Residuals, Yh0, R0, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RRPP_iterSS", (DL_FUNC) &_RRPP_iterSS, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_RRPP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
