// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sscXYopt
double sscXYopt(NumericMatrix X, NumericMatrix Y, int n1, int n2, int py, int px);
RcppExport SEXP _RRPP_sscXYopt(SEXP XSEXP, SEXP YSEXP, SEXP n1SEXP, SEXP n2SEXP, SEXP pySEXP, SEXP pxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< int >::type py(pySEXP);
    Rcpp::traits::input_parameter< int >::type px(pxSEXP);
    rcpp_result_gen = Rcpp::wrap(sscXYopt(X, Y, n1, n2, py, px));
    return rcpp_result_gen;
END_RCPP
}
