# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

shuffle <- function(Y, s) {
    .Call('_RRPP_shuffle', PACKAGE = 'RRPP', Y, s)
}

sscpUY <- function(U, Y) {
    .Call('_RRPP_sscpUY', PACKAGE = 'RRPP', U, Y)
}

iterSS <- function(ind, Ur, Uf, Ufull, Unull, Fitted, Residuals, Yh0, R0, k) {
    .Call('_RRPP_iterSS', PACKAGE = 'RRPP', ind, Ur, Uf, Ufull, Unull, Fitted, Residuals, Yh0, R0, k)
}

getCPsq <- function(ui, yi, Y) {
    .Call('_RRPP_getCPsq', PACKAGE = 'RRPP', ui, yi, Y)
}

getCPsq2 <- function(ui, yi, Y) {
    .Call('_RRPP_getCPsq2', PACKAGE = 'RRPP', ui, yi, Y)
}

getCPsq3 <- function(ui, yi) {
    .Call('_RRPP_getCPsq3', PACKAGE = 'RRPP', ui, yi)
}

getSS2 <- function(Y, s, ul, pl) {
    .Call('_RRPP_getSS2', PACKAGE = 'RRPP', Y, s, ul, pl)
}

sscpUycheck <- function(s, uj, u, y) {
    .Call('_RRPP_sscpUycheck', PACKAGE = 'RRPP', s, uj, u, y)
}

sscpUy <- function(s, uj, u, y) {
    .Call('_RRPP_sscpUy', PACKAGE = 'RRPP', s, uj, u, y)
}

