# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iterSS <- function(ind, Ur, Uf, Ufull, Unull, Fitted, Residuals, Yh0, R0, k) {
    .Call(`_RRPP_iterSS`, ind, Ur, Uf, Ufull, Unull, Fitted, Residuals, Yh0, R0, k)
}

