# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sscXYopt <- function(X, Y, n1, n2, py, px) {
    .Call('_RRPP_sscXYopt', PACKAGE = 'RRPP', X, Y, n1, n2, py, px)
}

